#
#	make for (sch)
#
# 

TOP	= ..
BIN	= ../DSSL_SOUND.exe
SRC	=   DSSL_SOUND_000.c DSSL_SOUND_101.c DSSL_SOUND_001.c \
	    DSSL_SOUND_102.c DSSL_SOUND_002.c DSSL_SOUND_006.c \
	    DSSL_SOUND_100.c sound_lib.c\

DEF	= -g -DDEBUG 
#DEF	= -g
#UCB	= -lucb
LCINC	=
LCLIB	= -lasound

include	$(TOP)/makedef/makeproc

#  DO NOT ERASE THIS LINE, make depend USE IT.
